# This file runs the server, web client, and some database things

version: "3.7"
services:
  server:
    build: ./services/server
    env_file:
      - .env
    environment:
      - PORT=80
    volumes:
      # mounting the docker socket allows the server to launch docker containers programatically
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/server:/usr/app
      - ./lib:/usr/app/turtus-lib
      - ./.env:/usr/app/.env
      - /usr/app/node_modules
    networks:
      - turtus-stack-network
  client:
    build: ./services/client
    env_file:
      - .env
    volumes:
      - ./services/client:/usr/app
      - ./.env:/usr/app/.env
      - ./lib:/usr/app/turtus-lib
      - /usr/app/node_modules
    networks:
      - turtus-stack-network
  nginx:
    image: nginx:alpine
    ports:
      - ${PORT:-80}:80
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - turtus-stack-network
    depends_on:
      - client
      - server
  redis:
    image: redis
  # This is a hack that allows us to build the virual browser from docker-compose 
  # but we're not going to run it immediately. This poses a slight problem with having
  # to rebuild the container manually whenever something change. Needs fixing
  virtual-browser:
    build: ./services/virtual-browser
    env_file:
      - .env
    command: echo virtual browser image available
networks:
  turtus-stack-network:
