# This file runs the server, web client, and some database things

version: "3.7"
services:
  server:
    build: ./services/server
    env_file:
      - .env
    environment:
      - PORT=80
    volumes:
      # mounting the docker socket allows the server to launch docker containers programatically
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/server:/usr/app
      - .env:/usr/app/.env
      - /usr/app/node_modules
    ports:
      - ${TURTUS_SERVER_PORT:-8080}:80
  client:
    build: ./services/client
    env_file:
      - .env
    volumes:
      - ./services/client:/usr/app
      - .env:/usr/app/.env
      - /usr/app/node_modules
    ports:
      - ${TURTUS_WEB_PORT:-80}:80
  redis:
    image: redis
  # This is a hack that allows us to build the virual browser from docker-compose but we're not going to run it
  virtual-browser:
    build: ./services/virtual-browser
    env_file:
      - .env
    command: echo virtual browser image available
